### PR TITLE
Update homebrew dependency version

### PR DESCRIPTION
**Pull request by kelleyDanger**

### CODE REVIEW

**Review by zirkov — CHANGES_REQUESTED** [review]
Same request as with the other repo: please update `metadata.rb` with the version to be `4.3.0` as well

**Comment by Brantone** [comment]
Squash commits + force push please.

**Comment by zirkov** [comment]
@Brantone I think it's better to just squash-merge and then force push the merge to local master — regardless of the path force push will happen but in any case we'd have a single commit in `Roblox:master`

**Comment by Brantone** [comment]
@zirkov  That's fair ... in such cases the person merging would just have to be aware of "squash+merge" 👍

**Review by zirkov — APPROVED** [review]

**Review by Brantone — APPROVED** [review]

**Pull request merged**
